FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04
RUN conda update -n base conda
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y  && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 8.0 8.6+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
ENV FORCE_CUDA="1"
ENV MMCV_WITH_OPS="1"
ENV SHELL /bin/bash
SHELL ["/bin/bash", "-c"]
